# Normal equation from skratch

### Import basic library and read data

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"market_data.csv")
df.head()

youtube  facebook  newspaper  sales
0    84.72     19.20      48.96  12.60
1   351.48     33.96      51.84  25.68
2   135.48     20.88      46.32  14.28
3   116.64      1.80      36.00  11.52
4   318.72     24.00       0.36  20.88

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   youtube    171 non-null    float64
 1   facebook   171 non-null    float64
 2   newspaper  171 non-null    float64
 3   sales      171 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB


In [4]:
df.duplicated().sum()

0

### Apply normal equation

##### Split data to x,y

In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
print (f"shape of x: {x.shape}")
print (f"shape of y: {y.shape}")

shape of x: (171, 3)
shape of y: (171,)


In [6]:
x_array=x.to_numpy()
x_array

array([[ 84.72,  19.2 ,  48.96],
       [351.48,  33.96,  51.84],
       [135.48,  20.88,  46.32],
       [116.64,   1.8 ,  36.  ],
       [318.72,  24.  ,   0.36],
       [114.84,   1.68,   8.88],
       [348.84,   4.92,  10.2 ],
       [320.28,  52.56,   6.  ],
       [ 89.64,  59.28,  54.84],
       [ 51.72,  32.04,  42.12],
       [273.6 ,  45.24,  38.4 ],
       [243.  ,  26.76,  37.92],
       [212.4 ,  40.08,  46.44],
       [352.32,  33.24,   2.16],
       [248.28,  10.08,  31.68],
       [ 30.12,  30.84,  51.96],
       [210.12,  27.  ,  37.8 ],
       [107.64,  11.88,  42.84],
       [287.88,  49.8 ,  22.2 ],
       [272.64,  18.96,  59.88],
       [ 80.28,  14.04,  44.16],
       [239.76,   3.72,  41.52],
       [120.48,  11.52,   4.32],
       [259.68,  50.04,  47.52],
       [219.12,  55.44,  70.44],
       [315.24,  34.56,  19.08],
       [238.68,  59.28,  72.  ],
       [  8.76,  33.72,  49.68],
       [163.44,  23.04,  19.92],
       [252.96,  59.52,  45.24],
       [25

In [7]:
n=len(x_array)
x_bias=np.ones((n,1))
x_bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [8]:
new_x=np.append(x_bias,x_array,axis=1)
new_x

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 

##### apply normal equation

In [9]:
new_x_t=new_x.T  # x_t -> x_transpose
new_x_t_dot_new_x=new_x_t.dot(new_x) # x_t . x
temp1=np.linalg.inv(new_x_t_dot_new_x) # (x_t * x) INVERSE
temp2=new_x_t.dot(y) # x_t . y
theta_hat=temp1.dot(temp2) # (x_t.x)INV .x_t .y
theta_hat

array([3.50587099, 0.04523544, 0.18839783, 0.00427949])

In [10]:
theta_0=theta_hat[0]
theta_1=theta_hat[1]
theta_2=theta_hat[2]
theta_3=theta_hat[3]

### Make predication

In [11]:
x1=x.iloc[:,0]
x2=x.iloc[:,1]
x3=x.iloc[:,2]
print (f"shape of x1: {x1.shape}")
print (f"shape of x1: {x2.shape}")
print (f"shape of x1: {x3.shape}")

shape of x1: (171,)
shape of x1: (171,)
shape of x1: (171,)


In [12]:
pred=theta_0+theta_1*x1+theta_2*x2+theta_3*x3
pred

0      11.164980
1      26.025064
2      13.766342
3       9.275311
4      22.446400
         ...    
166     6.486818
167     9.768662
168    15.249266
169    28.735611
170    18.093790
Length: 171, dtype: float64

### Evaluate model

In [13]:
from sklearn.metrics import mean_absolute_error, r2_score

print (f"mse = {mean_absolute_error(y,pred)}")
print (f"r2 score = {r2_score(y,pred)}")

mse = 1.4752261639040105
r2 score = 0.9004752358539351


### predication values

In [14]:
def pred_sales(youtube,facebook,news_paper):
    return (theta_0 + theta_1*youtube + theta_2*facebook + theta_3*news_paper)

youtube=84
facebook=19
news_paper=20
print (f"Sales = {pred_sales(youtube,facebook,news_paper)}" )

Sales = 10.970796845117416
